name: Reusable workflow for JASP code coverage

on:
  workflow_call:
    inputs:
      needs_JAGS:
        description: 'Should JAGS be available?'
        required: false
        type: boolean
        default: false
      continue_on_schedule:
        description: 'Should the workflow also be run on a schedule? By default (false), this only happens when the github.repository_owner is jasp-stats.'
        type: boolean
        default: false
    secrets:
      CODECOV_TOKEN:
        description: 'Token for Codecov upload'
        required: true

jobs:
  scheduled-run-check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check.outputs.status }}

    steps:
      - id: check
        run: echo "status=success" >> $GITHUB_OUTPUT
        if: inputs.continue_on_schedule == true || github.event_name != 'schedule' || github.repository_owner != 'jasp-stats'

  coverage:
    needs: scheduled-run-check
    if: needs.scheduled-run-check.outputs.status == 'success'

    runs-on: ubuntu-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_REMOTES_UPGRADE: never
      VDIFFR_RUN_TESTS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      _R_CHECK_LENGTH_1_CONDITION_: TRUE # deprecated from R 4.2.0
      _R_CHECK_MATRIX_DATA_: TRUE        # only works from R 4.2.0 onwards

    steps:
      - uses: actions/checkout@v5

      - name: Install system dependencies on linux
        if: runner.os == 'Linux'
        run: |
          sudo apt install libharfbuzz-dev libfribidi-dev libgit2-dev libcurl4-openssl-dev libicu*
        shell: bash

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
            github::jasp-stats/jaspTools
          needs: check
          cache-version: 0

      - name: Install JAGS on Linux
        if: runner.os == 'Linux' && inputs.needs_JAGS == true
        run: sudo apt install jags
        shell: bash

      - name: Setup jaspTools
        run: jaspTools::setupJaspTools()
        shell: Rscript {0}

      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          print(cov)
          covr::to_cobertura(cov)
        shell: Rscript {0}

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: ${{ github.event_name != 'pull_request' }}
          files: ./cobertura.xml
          plugins: noop
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
